# Dockerfile using stable Maxfuzz image
FROM coinbase/maxfuzz@sha256:f633dc8c2aff035f3e7668c83133dbb6fa7e9bf4372e6a28c2d8f86177385af6

WORKDIR /root/fuzzer-files
COPY ./fuzzers/ ./
COPY ./.git .
RUN chmod -R 755 /root/fuzzer-files
RUN echo "export GIT_SHA=$(git rev-parse HEAD)" >> /root/fuzzer-files/base/environment
